version: '3.7'

services:
  mongo1:
    image: mongo
    container_name: mongo1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongo_network
    command: ["--replSet", "rs0"]

  mongo2:
    image: mongo
    container_name: mongo2
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo_network
    command: ["--replSet", "rs0"]

  mongo3:
    image: mongo
    container_name: mongo3
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo_network
    command: ["--replSet", "rs0"]

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:

networks:
  mongo_network: